/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as SetoresRouteImport } from './routes/setores'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PermissoesRouteImport } from './routes/permissoes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GruposRouteImport } from './routes/grupos'
import { Route as FuncionariosRouteImport } from './routes/funcionarios'
import { Route as ExcluirContaRouteImport } from './routes/excluir-conta'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as AceitarConviteRouteImport } from './routes/aceitar-convite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiMobileWorkspacesRouteImport } from './routes/api/mobile/workspaces'
import { Route as ApiMobileTasksRouteImport } from './routes/api/mobile/tasks'
import { Route as ApiMobileTaskListsRouteImport } from './routes/api/mobile/task-lists'
import { Route as ApiMobileInvitationsRouteImport } from './routes/api/mobile/invitations'
import { Route as ApiMobileAccountRouteImport } from './routes/api/mobile/account'
import { Route as ApiMobileAuthGoogleRouteImport } from './routes/api/mobile/auth/google'
import { Route as ApiMobileAuthAppleRouteImport } from './routes/api/mobile/auth/apple'
import { Route as ApiMobileAuthEmailVerifyCodeRouteImport } from './routes/api/mobile/auth/email/verify-code'
import { Route as ApiMobileAuthEmailRequestCodeRouteImport } from './routes/api/mobile/auth/email/request-code'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const SetoresRoute = SetoresRouteImport.update({
  id: '/setores',
  path: '/setores',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissoesRoute = PermissoesRouteImport.update({
  id: '/permissoes',
  path: '/permissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposRoute = GruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionariosRoute = FuncionariosRouteImport.update({
  id: '/funcionarios',
  path: '/funcionarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcluirContaRoute = ExcluirContaRouteImport.update({
  id: '/excluir-conta',
  path: '/excluir-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const AceitarConviteRoute = AceitarConviteRouteImport.update({
  id: '/aceitar-convite',
  path: '/aceitar-convite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileWorkspacesRoute = ApiMobileWorkspacesRouteImport.update({
  id: '/api/mobile/workspaces',
  path: '/api/mobile/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileTasksRoute = ApiMobileTasksRouteImport.update({
  id: '/api/mobile/tasks',
  path: '/api/mobile/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileTaskListsRoute = ApiMobileTaskListsRouteImport.update({
  id: '/api/mobile/task-lists',
  path: '/api/mobile/task-lists',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileInvitationsRoute = ApiMobileInvitationsRouteImport.update({
  id: '/api/mobile/invitations',
  path: '/api/mobile/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileAccountRoute = ApiMobileAccountRouteImport.update({
  id: '/api/mobile/account',
  path: '/api/mobile/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileAuthGoogleRoute = ApiMobileAuthGoogleRouteImport.update({
  id: '/api/mobile/auth/google',
  path: '/api/mobile/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileAuthAppleRoute = ApiMobileAuthAppleRouteImport.update({
  id: '/api/mobile/auth/apple',
  path: '/api/mobile/auth/apple',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileAuthEmailVerifyCodeRoute =
  ApiMobileAuthEmailVerifyCodeRouteImport.update({
    id: '/api/mobile/auth/email/verify-code',
    path: '/api/mobile/auth/email/verify-code',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMobileAuthEmailRequestCodeRoute =
  ApiMobileAuthEmailRequestCodeRouteImport.update({
    id: '/api/mobile/auth/email/request-code',
    path: '/api/mobile/auth/email/request-code',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aceitar-convite': typeof AceitarConviteRoute
  '/calendario': typeof CalendarioRoute
  '/empresas': typeof EmpresasRoute
  '/excluir-conta': typeof ExcluirContaRoute
  '/funcionarios': typeof FuncionariosRoute
  '/grupos': typeof GruposRoute
  '/login': typeof LoginRoute
  '/permissoes': typeof PermissoesRoute
  '/privacidade': typeof PrivacidadeRoute
  '/relatorios': typeof RelatoriosRoute
  '/setores': typeof SetoresRoute
  '/tarefas': typeof TarefasRoute
  '/termos': typeof TermosRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mobile/account': typeof ApiMobileAccountRoute
  '/api/mobile/invitations': typeof ApiMobileInvitationsRoute
  '/api/mobile/task-lists': typeof ApiMobileTaskListsRoute
  '/api/mobile/tasks': typeof ApiMobileTasksRoute
  '/api/mobile/workspaces': typeof ApiMobileWorkspacesRoute
  '/api/mobile/auth/apple': typeof ApiMobileAuthAppleRoute
  '/api/mobile/auth/google': typeof ApiMobileAuthGoogleRoute
  '/api/mobile/auth/email/request-code': typeof ApiMobileAuthEmailRequestCodeRoute
  '/api/mobile/auth/email/verify-code': typeof ApiMobileAuthEmailVerifyCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aceitar-convite': typeof AceitarConviteRoute
  '/calendario': typeof CalendarioRoute
  '/empresas': typeof EmpresasRoute
  '/excluir-conta': typeof ExcluirContaRoute
  '/funcionarios': typeof FuncionariosRoute
  '/grupos': typeof GruposRoute
  '/login': typeof LoginRoute
  '/permissoes': typeof PermissoesRoute
  '/privacidade': typeof PrivacidadeRoute
  '/relatorios': typeof RelatoriosRoute
  '/setores': typeof SetoresRoute
  '/tarefas': typeof TarefasRoute
  '/termos': typeof TermosRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mobile/account': typeof ApiMobileAccountRoute
  '/api/mobile/invitations': typeof ApiMobileInvitationsRoute
  '/api/mobile/task-lists': typeof ApiMobileTaskListsRoute
  '/api/mobile/tasks': typeof ApiMobileTasksRoute
  '/api/mobile/workspaces': typeof ApiMobileWorkspacesRoute
  '/api/mobile/auth/apple': typeof ApiMobileAuthAppleRoute
  '/api/mobile/auth/google': typeof ApiMobileAuthGoogleRoute
  '/api/mobile/auth/email/request-code': typeof ApiMobileAuthEmailRequestCodeRoute
  '/api/mobile/auth/email/verify-code': typeof ApiMobileAuthEmailVerifyCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aceitar-convite': typeof AceitarConviteRoute
  '/calendario': typeof CalendarioRoute
  '/empresas': typeof EmpresasRoute
  '/excluir-conta': typeof ExcluirContaRoute
  '/funcionarios': typeof FuncionariosRoute
  '/grupos': typeof GruposRoute
  '/login': typeof LoginRoute
  '/permissoes': typeof PermissoesRoute
  '/privacidade': typeof PrivacidadeRoute
  '/relatorios': typeof RelatoriosRoute
  '/setores': typeof SetoresRoute
  '/tarefas': typeof TarefasRoute
  '/termos': typeof TermosRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mobile/account': typeof ApiMobileAccountRoute
  '/api/mobile/invitations': typeof ApiMobileInvitationsRoute
  '/api/mobile/task-lists': typeof ApiMobileTaskListsRoute
  '/api/mobile/tasks': typeof ApiMobileTasksRoute
  '/api/mobile/workspaces': typeof ApiMobileWorkspacesRoute
  '/api/mobile/auth/apple': typeof ApiMobileAuthAppleRoute
  '/api/mobile/auth/google': typeof ApiMobileAuthGoogleRoute
  '/api/mobile/auth/email/request-code': typeof ApiMobileAuthEmailRequestCodeRoute
  '/api/mobile/auth/email/verify-code': typeof ApiMobileAuthEmailVerifyCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aceitar-convite'
    | '/calendario'
    | '/empresas'
    | '/excluir-conta'
    | '/funcionarios'
    | '/grupos'
    | '/login'
    | '/permissoes'
    | '/privacidade'
    | '/relatorios'
    | '/setores'
    | '/tarefas'
    | '/termos'
    | '/api/health'
    | '/api/mobile/account'
    | '/api/mobile/invitations'
    | '/api/mobile/task-lists'
    | '/api/mobile/tasks'
    | '/api/mobile/workspaces'
    | '/api/mobile/auth/apple'
    | '/api/mobile/auth/google'
    | '/api/mobile/auth/email/request-code'
    | '/api/mobile/auth/email/verify-code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aceitar-convite'
    | '/calendario'
    | '/empresas'
    | '/excluir-conta'
    | '/funcionarios'
    | '/grupos'
    | '/login'
    | '/permissoes'
    | '/privacidade'
    | '/relatorios'
    | '/setores'
    | '/tarefas'
    | '/termos'
    | '/api/health'
    | '/api/mobile/account'
    | '/api/mobile/invitations'
    | '/api/mobile/task-lists'
    | '/api/mobile/tasks'
    | '/api/mobile/workspaces'
    | '/api/mobile/auth/apple'
    | '/api/mobile/auth/google'
    | '/api/mobile/auth/email/request-code'
    | '/api/mobile/auth/email/verify-code'
  id:
    | '__root__'
    | '/'
    | '/aceitar-convite'
    | '/calendario'
    | '/empresas'
    | '/excluir-conta'
    | '/funcionarios'
    | '/grupos'
    | '/login'
    | '/permissoes'
    | '/privacidade'
    | '/relatorios'
    | '/setores'
    | '/tarefas'
    | '/termos'
    | '/api/health'
    | '/api/mobile/account'
    | '/api/mobile/invitations'
    | '/api/mobile/task-lists'
    | '/api/mobile/tasks'
    | '/api/mobile/workspaces'
    | '/api/mobile/auth/apple'
    | '/api/mobile/auth/google'
    | '/api/mobile/auth/email/request-code'
    | '/api/mobile/auth/email/verify-code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AceitarConviteRoute: typeof AceitarConviteRoute
  CalendarioRoute: typeof CalendarioRoute
  EmpresasRoute: typeof EmpresasRoute
  ExcluirContaRoute: typeof ExcluirContaRoute
  FuncionariosRoute: typeof FuncionariosRoute
  GruposRoute: typeof GruposRoute
  LoginRoute: typeof LoginRoute
  PermissoesRoute: typeof PermissoesRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SetoresRoute: typeof SetoresRoute
  TarefasRoute: typeof TarefasRoute
  TermosRoute: typeof TermosRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMobileAccountRoute: typeof ApiMobileAccountRoute
  ApiMobileInvitationsRoute: typeof ApiMobileInvitationsRoute
  ApiMobileTaskListsRoute: typeof ApiMobileTaskListsRoute
  ApiMobileTasksRoute: typeof ApiMobileTasksRoute
  ApiMobileWorkspacesRoute: typeof ApiMobileWorkspacesRoute
  ApiMobileAuthAppleRoute: typeof ApiMobileAuthAppleRoute
  ApiMobileAuthGoogleRoute: typeof ApiMobileAuthGoogleRoute
  ApiMobileAuthEmailRequestCodeRoute: typeof ApiMobileAuthEmailRequestCodeRoute
  ApiMobileAuthEmailVerifyCodeRoute: typeof ApiMobileAuthEmailVerifyCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setores': {
      id: '/setores'
      path: '/setores'
      fullPath: '/setores'
      preLoaderRoute: typeof SetoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissoes': {
      id: '/permissoes'
      path: '/permissoes'
      fullPath: '/permissoes'
      preLoaderRoute: typeof PermissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos': {
      id: '/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof GruposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionarios': {
      id: '/funcionarios'
      path: '/funcionarios'
      fullPath: '/funcionarios'
      preLoaderRoute: typeof FuncionariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excluir-conta': {
      id: '/excluir-conta'
      path: '/excluir-conta'
      fullPath: '/excluir-conta'
      preLoaderRoute: typeof ExcluirContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aceitar-convite': {
      id: '/aceitar-convite'
      path: '/aceitar-convite'
      fullPath: '/aceitar-convite'
      preLoaderRoute: typeof AceitarConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/workspaces': {
      id: '/api/mobile/workspaces'
      path: '/api/mobile/workspaces'
      fullPath: '/api/mobile/workspaces'
      preLoaderRoute: typeof ApiMobileWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/tasks': {
      id: '/api/mobile/tasks'
      path: '/api/mobile/tasks'
      fullPath: '/api/mobile/tasks'
      preLoaderRoute: typeof ApiMobileTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/task-lists': {
      id: '/api/mobile/task-lists'
      path: '/api/mobile/task-lists'
      fullPath: '/api/mobile/task-lists'
      preLoaderRoute: typeof ApiMobileTaskListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/invitations': {
      id: '/api/mobile/invitations'
      path: '/api/mobile/invitations'
      fullPath: '/api/mobile/invitations'
      preLoaderRoute: typeof ApiMobileInvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/account': {
      id: '/api/mobile/account'
      path: '/api/mobile/account'
      fullPath: '/api/mobile/account'
      preLoaderRoute: typeof ApiMobileAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/auth/google': {
      id: '/api/mobile/auth/google'
      path: '/api/mobile/auth/google'
      fullPath: '/api/mobile/auth/google'
      preLoaderRoute: typeof ApiMobileAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/auth/apple': {
      id: '/api/mobile/auth/apple'
      path: '/api/mobile/auth/apple'
      fullPath: '/api/mobile/auth/apple'
      preLoaderRoute: typeof ApiMobileAuthAppleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/auth/email/verify-code': {
      id: '/api/mobile/auth/email/verify-code'
      path: '/api/mobile/auth/email/verify-code'
      fullPath: '/api/mobile/auth/email/verify-code'
      preLoaderRoute: typeof ApiMobileAuthEmailVerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/auth/email/request-code': {
      id: '/api/mobile/auth/email/request-code'
      path: '/api/mobile/auth/email/request-code'
      fullPath: '/api/mobile/auth/email/request-code'
      preLoaderRoute: typeof ApiMobileAuthEmailRequestCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AceitarConviteRoute: AceitarConviteRoute,
  CalendarioRoute: CalendarioRoute,
  EmpresasRoute: EmpresasRoute,
  ExcluirContaRoute: ExcluirContaRoute,
  FuncionariosRoute: FuncionariosRoute,
  GruposRoute: GruposRoute,
  LoginRoute: LoginRoute,
  PermissoesRoute: PermissoesRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RelatoriosRoute: RelatoriosRoute,
  SetoresRoute: SetoresRoute,
  TarefasRoute: TarefasRoute,
  TermosRoute: TermosRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMobileAccountRoute: ApiMobileAccountRoute,
  ApiMobileInvitationsRoute: ApiMobileInvitationsRoute,
  ApiMobileTaskListsRoute: ApiMobileTaskListsRoute,
  ApiMobileTasksRoute: ApiMobileTasksRoute,
  ApiMobileWorkspacesRoute: ApiMobileWorkspacesRoute,
  ApiMobileAuthAppleRoute: ApiMobileAuthAppleRoute,
  ApiMobileAuthGoogleRoute: ApiMobileAuthGoogleRoute,
  ApiMobileAuthEmailRequestCodeRoute: ApiMobileAuthEmailRequestCodeRoute,
  ApiMobileAuthEmailVerifyCodeRoute: ApiMobileAuthEmailVerifyCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
